services:
  blog:
    build: .
    container_name: smeuse-blog
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REVALIDATE_SECRET=${REVALIDATE_SECRET}
    volumes:
      - /mnt/d/develop/source/blog/content:/app/content
      - /mnt/d/develop/source/blog/data:/app/data
      - /mnt/d/develop/source/blog/public/images:/app/public/images
